blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('projects/', views.projects, name='projects'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name='blog'),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts': posts})

def projects(request):
    return render(request, 'blog/projects.html')

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edreinne's Links</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <style>
    body {
      background-color: #1a1a1a;
      color: #ffffff;
    }
    .navbar {
      border-bottom: 1px solid #343a40;
    }
    .nav-link {
      color: rgba(255, 255, 255, 0.75) !important;
    }
    .nav-link:hover {
      color: #ffffff !important;
    }
    .border-bottom {
      border-bottom-color: #343a40 !important;
    }
  </style>
</head>
<body class="bg-dark">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'blog:post_list' %}">
        Edreinne's Links</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="https://tinyurl.com/esumabat">
              My Resume </a></li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/edsumabat">
              My Github </a></li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:projects' %}">
              My Projects </a></li>
        </ul>
      </div>
    </div>
  </nav>

  <main class="container text-white">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>

    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>

</body>
</html>

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-dark text-white border-dark rounded-3">
        <div class="container-fluid py-4">
            <h5 class="display-7">About me.</h5>

            <p class="lead">Hello everyone! I am Engr. Edreinne Dizon Sumabat, ECT. 
                I graduated with an Electronics and Communications Engineering degree, and recently 
                passed the ECELE and ranked third in ECTLE (October 2024). I am 
                currently studying for my CCNA certification and furthering my 
                skills as a developer at the same time. I am furthering my skills in these areas 
                because my passion is towards IT and development. I am looking forward to 
                applying and contributing my skills in the IT industry.

                This website is to document my future projects.
            </p>
            <a class="btn btn-primary btn-lg mt-1" href="{% url 'blog:projects' %}">Show projects &raquo;</a>
        </div>
    </div>
{% endblock page_header %}


{% block content %}
    {% for post in posts %}
    <div class="card mb-3 bg-secondary text-light">
        <h5 class="card-header">
           {{ post.title }} ({{ post.published_date}})
        </h5>
         <div class="card-body bg-dark rounded-1">
           <p class="card-text text-light">{{ post.text }}</p>
         </div>
   </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/projects.html
{% extends 'blog/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <div class="p-3 bg-dark text-white border-dark rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">My Projects</h1>
        </div>
    </div>
{% endblock page_header %}

{% block content %}
    <div class="container">
        <div class="card mb-3 bg-secondary text-light">
            <h5 class="card-header">Project Links</h5>
            <div class="card-body bg-dark rounded-1">
                <ul class="list-group">
                    <li class="list-group-item bg-dark border-dark">
                        <a href="https://github.com/edsumabat/my-landing-page" class="list-group-item list-group-item-action bg-secondary text-light">
                            My portfolio page / homepage. (This website)
                        </a>
                    </li>
                    <li class="list-group-item bg-dark border-0">
                        <a href="https://edsumabat2.pythonanywhere.com/" class="list-group-item list-group-item-action bg-secondary text-light">
                            Blog and Log, a multi-user blog demo.
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}